# Generated by Django 3.2.12 on 2022-02-01 15:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.core.fields.StreamField([('titre_et_text', wagtail.core.blocks.StructBlock([('titre', wagtail.core.blocks.CharBlock(help_text="titre d'article ", required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='les contenues ', required=True))]))], blank=True, null=True),
        ),
    ]
