# Generated by Django 3.2.12 on 2022-02-02 18:47

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.core.fields.StreamField([('titre_et_text_block', wagtail.core.blocks.StructBlock([('titre', wagtail.core.blocks.CharBlock(help_text="titre d'article ", required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='les contenues ', required=True))])), ('richtext_block', streams.blocks.RichtextBlock())], blank=True, null=True),
        ),
    ]
